### ISSUE TITLE
Not working with 1.4 update

### ISSUE THREAD

**Issue by Leoracle25** [Brian-Wuest/Instacrops#1]
Not sure if anyone had messaged you or made you aware that your mod isn't working currently 1.4, I just wanted to check in out of curiosity (Cause I love using this mod) if you were going to be updating it so that it can be used in 1.4 or if you're ceasing your work on the mod at this time?

**Comment by Brian-Wuest** [comment]
This mod is no longer going to be supported. There just isn't time to manage it. Sorry.
